// Generated by koya-ts-sdk (`koya types`) from a koya schema. Do not edit.

import type * as koya from "../../src/index.ts";

/** `blog` as stored: media and references are ids. */
export interface BlogData {
  title: string;
  slug?: string | null;
  cover?: string | null;
  content?: string | null;
  category?: "tech" | "life" | null;
  author?: string | null;
  tags?: string[] | null;
}

/** `blog` as delivered, without the system fields. */
export interface BlogFields {
  title: string;
  slug?: string | null;
  cover?: koya.Media | null;
  content?: string | null;
  category?: "tech" | "life" | null;
  author?: string | null;
  tags?: string[] | null;
}

/** `author` as stored: media and references are ids. */
export interface AuthorData {
  name: string;
  avatar?: string | null;
  mentor?: string | null;
}

/** `author` as delivered, without the system fields. */
export interface AuthorFields {
  name: string;
  avatar?: koya.Media | null;
  mentor?: string | null;
}

/** `tag` as stored: media and references are ids. */
export interface TagData {
  name: string;
}

/** `tag` as delivered, without the system fields. */
export interface TagFields {
  name: string;
}

/** `site-settings` as stored: media and references are ids. */
export interface SiteSettingsData {
  maintenance: boolean;
  postsPerPage?: number | null;
}

/** `site-settings` as delivered, without the system fields. */
export interface SiteSettingsFields {
  maintenance: boolean;
  postsPerPage?: number | null;
}

export type KoyaModels = {
  "blog": {
    kind: "list";
    data: BlogData;
    fields: BlogFields;
    refs: { "author": { model: "author"; many: false }; "tags": { model: "tag"; many: true } };
  };
  "author": {
    kind: "list";
    data: AuthorData;
    fields: AuthorFields;
    refs: { "mentor": { model: "author"; many: false } };
  };
  "tag": {
    kind: "list";
    data: TagData;
    fields: TagFields;
    refs: {};
  };
  "site-settings": {
    kind: "object";
    data: SiteSettingsData;
    fields: SiteSettingsFields;
    refs: {};
  };
};
