// Generated by koya-ts-sdk (`koya types`) from a koya schema. Do not edit.

import type * as koya from "../../src/index.ts";

/** `blog` as stored: media and references are ids. */
export interface BlogData {
  /** Shown in lists and the page title */
  title: string;
  slug?: string | null;
  cover?: string | null;
  content?: string | null;
  category?: "tech" | "life" | null;
  author?: string | null;
  tags?: string[] | null;
  gallery?: string[] | null;
  meta?: SeoData | null;
  blocks: (({ fieldId: "heading" } & HeadingData) | ({ fieldId: "quote" } & QuoteData))[];
}

/** `blog` as delivered, without the system fields. */
export interface BlogFields {
  /** Shown in lists and the page title */
  title: string;
  slug?: string | null;
  cover?: koya.Media | null;
  content?: string | null;
  category?: "tech" | "life" | null;
  author?: string | null;
  tags?: string[] | null;
  gallery?: koya.Media[] | null;
  meta?: SeoFields | null;
  blocks: (({ fieldId: "heading" } & HeadingFields) | ({ fieldId: "quote" } & QuoteFields))[];
}

/** `author` as stored: media and references are ids. */
export interface AuthorData {
  name: string;
  avatar?: string | null;
  mentor?: string | null;
}

/** `author` as delivered, without the system fields. */
export interface AuthorFields {
  name: string;
  avatar?: koya.Media | null;
  mentor?: string | null;
}

/** `tag` as stored: media and references are ids. */
export interface TagData {
  name: string;
}

/** `tag` as delivered, without the system fields. */
export interface TagFields {
  name: string;
}

/** `site-settings` as stored: media and references are ids. */
export interface SiteSettingsData {
  maintenance: boolean;
  postsPerPage?: number | null;
}

/** `site-settings` as delivered, without the system fields. */
export interface SiteSettingsFields {
  maintenance: boolean;
  postsPerPage?: number | null;
}

/** The custom field `seo` as stored: media and references are ids. */
export interface SeoData {
  title?: string | null;
  /** 1200x630 */
  image?: string | null;
  author?: string | null;
}

/** The custom field `seo` as delivered. */
export interface SeoFields {
  title?: string | null;
  /** 1200x630 */
  image?: koya.Media | null;
  author?: string | null;
}

/** The custom field `heading` as stored: media and references are ids. */
export interface HeadingData {
  text: string;
}

/** The custom field `heading` as delivered. */
export interface HeadingFields {
  text: string;
}

/** The custom field `quote` as stored: media and references are ids. */
export interface QuoteData {
  text: string;
  by?: string[] | null;
}

/** The custom field `quote` as delivered. */
export interface QuoteFields {
  text: string;
  by?: string[] | null;
}

export type KoyaModels = {
  "blog": {
    kind: "list";
    data: BlogData;
    fields: BlogFields;
    refs: { "author": { model: "author"; many: false }; "tags": { model: "tag"; many: true }; "meta": { custom: { "author": { model: "author"; many: false } } }; "blocks": { rows: { "quote": { "by": { model: "author"; many: true } } } } };
  };
  "author": {
    kind: "list";
    data: AuthorData;
    fields: AuthorFields;
    refs: { "mentor": { model: "author"; many: false } };
  };
  "tag": {
    kind: "list";
    data: TagData;
    fields: TagFields;
    refs: {};
  };
  "site-settings": {
    kind: "object";
    data: SiteSettingsData;
    fields: SiteSettingsFields;
    refs: {};
  };
};
