import type { Field, Model, Schema } from "./generated/koya.ts";

function typeName(model: string): string {
  return model.replace(/(^|-)([a-z0-9])/g, (_, _dash, c: string) => c.toUpperCase());
}

function valueType(field: Field, delivered: boolean): string {
  switch (field.type) {
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "select": {
      const one = field.options.map((o) => JSON.stringify(o)).join(" | ");
      return field.many ? `(${one})[]` : one;
    }
    case "reference":
      return field.many ? "string[]" : "string";
    case "media":
      // a media whose file is gone is delivered as null, required or not
      return delivered ? "koya.Media | null" : "string";
    default:
      return "string";
  }
}

function property(field: Field, delivered: boolean): string {
  const type = valueType(field, delivered);
  if (field.required) return `  ${field.name}: ${type};`;
  return `  ${field.name}?: ${type.endsWith("| null") ? type : `${type} | null`};`;
}

function modelTypes(model: Model): string {
  const name = typeName(model.name);
  const fields = model.fields ?? [];
  const body = (delivered: boolean) => (fields.length ? `{\n${fields.map((f) => property(f, delivered)).join("\n")}\n}` : "{}");
  return [
    `/** \`${model.name}\` as stored: media and references are ids. */`,
    `export interface ${name}Data ${body(false)}`,
    "",
    `/** \`${model.name}\` as delivered, without the system fields. */`,
    `export interface ${name}Fields ${body(true)}`,
  ].join("\n");
}

function modelEntry(model: Model): string {
  const name = typeName(model.name);
  const refs = (model.fields ?? [])
    .filter((f) => f.type === "reference")
    .map((f) => `${JSON.stringify(f.name)}: { model: ${JSON.stringify(f.model)}; many: ${f.many ? "true" : "false"} }`);
  return [
    `  ${JSON.stringify(model.name)}: {`,
    `    kind: ${JSON.stringify(model.kind)};`,
    `    data: ${name}Data;`,
    `    fields: ${name}Fields;`,
    `    refs: ${refs.length ? `{ ${refs.join("; ")} }` : "{}"};`,
    "  };",
  ].join("\n");
}

/**
 * TypeScript declarations for a schema: per model `<Name>Data` and
 * `<Name>Fields`, and `KoyaModels`, which `createClient` and `createAdminClient` take.
 */
export function generateTypes(schema: Schema, { from = "koya-ts-sdk" }: { from?: string } = {}): string {
  const models = schema.models ?? [];
  const names = new Map<string, string>();
  for (const model of models) {
    const name = typeName(model.name);
    const other = names.get(name);
    if (other) throw new Error(`models ${other} and ${model.name} would both be typed ${name}`);
    names.set(name, model.name);
  }
  return [
    "// Generated by koya-ts-sdk (`koya types`) from a koya schema. Do not edit.",
    "",
    `import type * as koya from ${JSON.stringify(from)};`,
    "",
    ...models.flatMap((m) => [modelTypes(m), ""]),
    // a type alias, not an interface, so that it is assignable to ModelMap's index signature
    "export type KoyaModels = {",
    ...models.map(modelEntry),
    "};",
    "",
  ].join("\n");
}
